name: Googshepro

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build after push
    runs-on: node:14

    steps:
      - uses: actions/checkout@v2
      #- name: run
      #  run: echo ">>> Build <<<"
      - uses: ./action-a
        with:
          KEY: "1747" 
      
 #     - name: run
 #       run: docker run --rm -it --env-file .env -p 8100:8000 --name gsproxy Jnqa/gsproxy
