name: Googshepro

on: push

jobs:
  job1:
    name: Build after push
    runs-on: ubuntu-latest
    steps:
    #- id: step1
    # - uses: actions/checkout@v2
    - id: step1
      run: echo ">>> Build <<<"
    - id: step2
      run: docker build -t jnqa/googlesheetsproxy .
    - id: step3
      run: echo "<<< Complete! >>>"
    - id: step4
      run: read var1
    - id: step5
      run: echo "step 5 >> $var1"
      
 #     - name: run
 #       run: docker run --rm -it --env-file .env -p 8100:8000 --name gsproxy Jnqa/gsproxy
