name: Googshepro

on: push

jobs:
  build:
    name: Build after push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #- name: run
      #  run: echo ">>> Build <<<"
      - name: Build
        run: docker build -t jnqa/googlesheetsproxy .
      
 #     - name: run
 #       run: docker run --rm -it --env-file .env -p 8100:8000 --name gsproxy Jnqa/gsproxy
