name: Googshepro

on: push

jobs:
  job1:
    name: Build after push
    runs-on: ubuntu-latest
    steps:
    - name: akshon
      uses: actions/checkout@v2
    - name: Say Build
      run: echo ">>> Build <<< -- Useless you know?"
    - name: docker-magic
      run: docker build -t jnqa/googlesheetsproxy .
    - name: Say Good News
      run: echo "<<< Complete! >>> -- Useless you know?"
  job2:
    name: Second thread
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "Second process"

 # +
 #     - name: run
 #       run: docker run --rm -it --env-file .env -p 8100:8000 --name gsproxy Jnqa/gsproxy
