# This is a basic workflow to help you get started with Actions

name: WhatIsThis

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: WhatAndWhere
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: bulid
        run: docker build -t Jnqa/gsproxy .
      
      - name: run
        run: docker run --rm -it --env-file .env -p 8100:8000 --name gsproxy Jnqa/gsproxy
